openapi: 3.0.0
info:
  title: Adressbuch
  description: "Die Adressbuch-App nutzt einen simplen REST-Webservices zur Kommunikation\
    \ mit dem Backend. Dieser ermöglicht die üblichen CRUD-Operationen zur Suche,\
    \ Anzeige, Bearbeitung und Löschung von Adressen, wobei jede Adresse aus einem\
    \ Vornamen, Nachnamen, Telefonnummer und eine E-Mailadresse besteht."
  contact:
    name: Bastian Hecek
    url: https://www.wpvs.de
    email: dhbw@windows3.de
  license:
    name: CC-BY-4.0
    url: https://creativecommons.org/licenses/by/4.0/deed.de
  version: "1.0"
servers:
- url: http://localhost:3000
tags:
- name: Index
- name: Termin
paths:
  /:
    get:
      tags:
      - Index
      summary: Wurzeladresse des Webservices
      description: Liefert eine HATEOAS-Übersicht aller collections
      operationId: index
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HATEOAS_Collection'
                x-content-type: application/json

  /termine:
    get:
      tags:
      - Termin
      summary: Termine suchen
      description: Suche nach Termine. Gibt eine Liste aller Termine passend zu
        den übergebenen Suchkriterien zurück.
      operationId: search-termin
      parameters:
      - name: title
        in: query
        description: Termintitel
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: date
        in: query
        description: Datum in "10.10.2010"
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: duration
        in: query
        description: Dauer des Termins
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: kind
        in: query
        description: Ist es ein ToDo oder ein Termin in "termin" oder "todo"
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/termine'
                x-content-type: application/json
    post:
      tags:
      - Termin
      summary: Termin anlegen
      description: "Neue Termine anlegen. Speichert die übergebene Adresse in der\
        \ Datenbank. Der Wert des Feldes \"_id\" wird dabei ignoriert, da in jedem Fall\
        \ eine neuer Termin mit neuer ID angelegt wird."
      operationId: create-termin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/termine'
      responses:
        "201":
          description: Created
          headers:
            Location:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/termine'

  /termine/{id}:
    get:
      tags:
      - Termin
      summary: Termin lesen
      description: Liest ein einzelnen Termin vom Server.
      operationId: get-termin
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/termine'
        "404":
          description: Not Found
    put:
      tags:
      - Termin überschreiben
      summary: ""
      description: "Überschreibt einen vorhandenen Termin auf dem Server. Bis auf die\
        \ ID können alle Felder geändert werden. Der Versuch, die ID zu ändern, wird\
        \ vom Server stillschweigend ignoriert."
      operationId: update-termin
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/termine'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/termine'
        "404":
          description: Not Found
    patch:
      tags:
      - Einzelne Felder ändern
      summary: Einzelne Terminfelder ändern
      description: "Ändert einzelne Felder eines vorhandenen Termins. Zulässig sind\
        \ alle Felder bis auf die ID, da diese nachträglich nicht mehr verändert werden\
        \ darf."
      operationId: patch-termin
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/termine'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/termine'
        "404":
          description: Not Found
    delete:
      tags:
      - Termin
      summary: Termin löschen
      description: Löscht einen Termin auf dem Server.
      operationId: delete-termin
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "204":
          description: OK
        "404":
          description: Not Found
        

components:
  schemas:
    HATEOAS_Collection:
      title: HATEOAS-Links einer Collection
      type: object
      properties:
        _name:
          type: string
        query:
          $ref: '#/components/schemas/HATEOAS_Link'
        create:
          $ref: '#/components/schemas/HATEOAS_Link'

    HATEOAS_Resource:
      title: HATEOAS-Links einer Resource
      type: object
      properties:
        read:
          $ref: '#/components/schemas/HATEOAS_Link'
        update:
          $ref: '#/components/schemas/HATEOAS_Link'
        patch:
          $ref: '#/components/schemas/HATEOAS_Link'
        delete:
          $ref: '#/components/schemas/HATEOAS_Link'

    HATEOAS_Link:
      title: HATEOAS-Link
      type: object
      properties:
        url:
          type: string
        method:
          type: string
        query_params:
          type: array
          items:
            type: string

    termine:
      title: Termine
      type: object
      properties:
        _links:
          $ref: '#/components/schemas/HATEOAS_Resource'
        _id:
          type: string
        title:
          type: string
        date:
          type: string
        duration:
          type: integer
        kind:
          type: string
      required:
        - title
        - kind
      example:
        _id: "621ff9a936997df5baba746e"
        title: "Abendessen"
        date: "24.12.2022 12:00:00"
        duration: 45
        kind: "termin"
  securitySchemes: {}
